apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-app
  labels:
    app: healthcare
spec:
  replicas: 3  # Number of instances of your app
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
        - name: healthcare-container
          image: adityaprakash27/healthcare:latest  # Replace with your actual Docker image
          ports:
            - containerPort: 80  # Port on which your app is listening
          env:
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              value: "mysql://user:password@database-server:3306/dbname"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
spec:
  selector:
    app: healthcare
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 80  # Port on which your container listens
  type: LoadBalancer  # To create an external load balancer (for cloud)
