apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
spec:
  selector:
    app: healthcare  # Must match the label defined in the Deployment
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 80  # Port on which the app is running inside the pod
  type: LoadBalancer  # External load balancer to access your service
